### PR TITLE
resolved 404 to polymer elements

### PR DESCRIPTION
**Pull request by ronlobo**

### CODE REVIEW

**Comment by jakemac53** [comment]
sorry one more thing - would you mind squashing these commits?

**Comment by ronlobo** [comment]
Sure

**Comment by jakemac53** [comment]
fyi, you shouldn't have to close these pull requests, you can just force push to your branch and the PR will update

**Comment by ronlobo** [comment]
Ok, thanks, so it is 'git push -f' I guess.

**Comment by jakemac53** [comment]
yep!

**Comment by ronlobo** [comment]
Ok, then I think the squashing was ok, but to pull remotely was unnecessary, thanks a lot!

**Pull request closed without merging**
